// RootLayout.js
import { Inter } from 'next/font/google';
import './globals.css';

import Link from 'next/link';
import SparklesImg from '@/components/SparklesImg';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-gradient-to-b from-bg-gradient-from to-bg-gradient-to min-h-screen'}>
        <main className="p-6">
          <header className='flex flex-row justify-between mt-5'>
            <Link href='/' className='flex flex-row gap-2 items-center text-white'>
              <SparklesImg className='w-6 h-6' />
              <span className='text-3xl font-bold'>Caption</span>
            </Link>
            <nav className='flex gap-6 text-white border border-[#f64c72] rounded-l items-center p-4 text-xl'>
              <Link href='/'>Home</Link>
              <Link href='/pricing'>Price</Link>
              <a href="mailto:contact@epiccaptions.com">Contact</a>
            </nav>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
